# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'catch_geometry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for catch_geometry

  target 'catch_geometryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'catch_geometryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
